### ISSUE TITLE
Ablation Study for the char-level RNN model

### ISSUE THREAD

**Issue by ws-choi** [Intelligence-Engineering-LAB-KU/Seminar#3]
지난번 RNN code (d4b49dcc1728d71ba3e82a754c7d0aefc4ebcbc3)([link](https://github.com/Intelligence-Engineering-LAB-KU/Seminar/blob/d4b49dcc1728d71ba3e82a754c7d0aefc4ebcbc3/summer_2020/intern1/RNN/RNN.ipynb)) 와 제대로 동작하는 RNN code를 비교하고

[ablation study](https://www.quora.com/In-the-context-of-deep-learning-what-is-an-ablation-study)를 통해
어떤 요소가 문제를 일으키는 주 원인이었는지 공유해주신다면 다른 사람들에게도 많은 도움이 될 듯 합니다.

**Comment by ws-choi** [comment]
왜안해

**Comment by nemo-algorithm** [comment]
@ws-choi
https://drive.google.com/file/d/1lYfOX_lpspNfpZBEPfB1ccwz42Fe_oWi/view?usp=sharing

**Comment by nemo-algorithm** [comment]
@ws-choi 
https://github.com/Intelligence-Engineering-LAB-KU/Seminar/blob/master/summer_2020/intern1/4.%20Vanilla_RNN%20%EC%8B%A4%EC%8A%B5%20with%20numpy/5.%20Vanilla_RNN.ipynb

편하게 보려면
https://drive.google.com/file/d/1lYfOX_lpspNfpZBEPfB1ccwz42Fe_oWi/view?usp=sharing
